# Llamadas de prueba a /api/categories.
### Alta rubro
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Escolar"
}

### Alta subcategoría (cambiar parentId)
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Cuadernos a4",
  "parentId": 1
}

### Listado
GET http://localhost:8080/api/categories

### Una categoría (cambiar el id)
GET http://localhost:8080/api/categories/1

### Editar
PUT http://localhost:8080/api/categories/2
Content-Type: application/json

{
  "name": "Cuadernos A4",
  "parentId": 1
}

### Baja lógica
DELETE http://localhost:8080/api/categories/3

### Reactivar
POST http://localhost:8080/api/categories/3/activate
